### ISSUE TITLE
 Error import and compiling 

### ISSUE THREAD

**Issue by Profnird** [muratoner/semantic-ui-react-native#9]
./node_modules/@muratoner/semantic-ui-react-native/src/ui/Center.js 12:2
Module parse failed: Unexpected token (12:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|       } = props
|       return (
>               <View
|                       {...attributes}
|                       style={[{alignItems, justifyContent, flexDirection}, style]}
./node_modules/@muratoner/semantic-ui-react-native/src/ui/Inset.js 18:2
Module parse failed: Unexpected token (18:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

**Comment by muratoner** [comment]
What type of project do you want to run? react native or react? If you are want use in react project then this package is not compatible for react project.

**Comment by Profnird** [comment]
Using it for React Native.

**Comment by muratoner** [comment]
What is your react-native version?
